language: objective-c
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    secure: ON1oO0Ehm0Wdh9hMKhfuU9ZNbLj/lou/zOxPwjRyYo0YvBbCwuAWik/ozh6Svq3/BdPsEHgt0GOZeS9/BsLdk8z9QvroJb5Uc7Q951xmT2SzMSEpi8t7OPeQ5YRoCR3F3PhExQI/jrCiWedf/sMYTrdwMQWz15fLuvGQWZ7cjbIa51YJ0foBfaZFXk77UJdPiMjEPmvlsvZ95mH5NtZ/hkb9KIjHtmw3V6Mzp+gnuY4u3i0kCaXWgqdxphTMgw/zIxQ8hBsl27esKZG+3PaU7IKtO0GPbiAlxkJkVIV76sXhDPhH6KBxUb1d9wlGSHAz4Y9n5K7MyWN0123P6Mxf6x7MNMy6/0ZFS0kFTuxfPJODGNRa5PulJT9t5NZ9F4Iq6pQxswuM8anok5qUcniEF+2SLmOT9StrDqFpJVjp+i/xl7vJzkM3gVyG3G9o/miBMuIQZXXAfuZAaOLHN9WWQrymKiYkDd6AXXzHD1Dlt4WXwIFac5QjlAJH+bUZIIqrIFJ7MJOZp81hFTkJIqq1cQHXJa13rU19XvzvEwdLSm4+rwl+q2JByICxizP3lp0VjvmcjuAFwAPg7NqpoHI2o5Tu3d8NL8Tyf9Nu8HuKZt15/O5/jifwoBUsk4FuoHki6iMnzYzVrZgLcGJzhf5uBWu/Rup3/Exyy7vsTyFpf5U=
matrix:
  include:
  - osx_image: xcode10
before_install:
  - brew install clang-format
  - mkdir bin
  - curl -Ls "https://raw.githubusercontent.com/llvm-mirror/clang/c510fac5695e904b43d5bf0feee31cc9550f110e/tools/clang-format/git-clang-format" -o "bin/git-clang-format"
  - chmod +x bin/git-clang-format
  - export PATH="$(pwd)/bin:$PATH"
script:
  - if [ -n "$TRAVIS_PULL_REQUEST_SLUG" ]; then ./check-pull-request.sh --api_token "$GITHUB_TOKEN" --repo "$TRAVIS_PULL_REQUEST_SLUG" --pr "$TRAVIS_PULL_REQUEST" --commit "$TRAVIS_PULL_REQUEST_SHA" --target_branch "$TRAVIS_BRANCH"; fi
