language: objective-c
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    secure: GT0DRUuVxHjJqUzGyYmqvICrPICoX0SZUd0cMqaUyTAoaTodbYn8KctJ3YJ23eDdSAG4qq9+cNtJq4cV2MBW3Ehuy+SRQhbGFQTxpQk90B2Tj2ZNxnuotpsJSHVryxp/Mxyk3beBWrkQ4vtOYvF9szaJB+xCMH5y+VGffm7iEJze3zn4SsK35+TgfV2ju2LSTQgj4/mdcNd530meCTidtxfpaN6ooscoFqKCflzXvxnkCleOglTPE4sV+ZJb2ImvTyqL6w7dBBD2O0C4bxSq4CR0eLPzMNsw6FXNS+WHIDzch8H5shVvtrtXFmhk6ifelxRd4l0IuCQsQx9xIoUgXOevzJV00HouD1nd/20MTI47Q2j/YY4OJK0C4grWkzbVAdagRYyXDAW32ORp4thjuVR9+uwTeGJfudk/7JXBzexGjMzbuujAyisLI7r0wcT5GyKfGDV3z+BK0LlYy6EeaJGf4ZG2cXxsVNMyBxziedYRVk/s/R9Q4uWmgybghqDd9P5YmZYAd86HqFNSXMy7wlUw5yqqL9bC/8BELzc07hXfzJbPVpHhcPcYh7zn6ToPPGfrAFl8LJ8DbsUMEvmhF+1GvrLD5FzTtcmgWJY4C1XtzY7L6iZ/DREOgDiyAHqWyRxqCFvxmuDV62GmyER7sEGrkROEteXbBpchnMccH8k=
matrix:
  include:
  - osx_image: xcode10
before_install:
  - brew install clang-format
  - mkdir bin
  - curl -Ls "https://raw.githubusercontent.com/llvm-mirror/clang/c510fac5695e904b43d5bf0feee31cc9550f110e/tools/clang-format/git-clang-format" -o "bin/git-clang-format"
  - chmod +x bin/git-clang-format
  - export PATH="$(pwd)/bin:$PATH"
script:
  - if [ -n "$TRAVIS_PULL_REQUEST_SLUG" ]; then ./check-pull-request.sh --api_token "$GITHUB_TOKEN" --repo "$TRAVIS_PULL_REQUEST_SLUG" --pr "$TRAVIS_PULL_REQUEST" --commit "$TRAVIS_PULL_REQUEST_SHA" --target_branch "$TRAVIS_BRANCH"; fi
